// Chaddha Fashion - the one and only product catalogue.
//
// Every page reads its products from this file, so adding a product or
// fixing a price is a one-line change that shows up across the whole site.

// Apparel is sold in size runs, so we keep the common runs in one place.
const SIZE_RUNS = {
  adult: ['S', 'M', 'L', 'XL', 'XXL'],
  kids: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
  free: ['Free Size']
};

const PRODUCTS = [
  // ---------------- Men ----------------
  {
    id: 1,
    name: 'Men White T-Shirt',
    price: 899,
    image: './Men Tshirt image 1.avif',
    category: 'men',
    subcategory: 'Men T-Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'A clean white crew-neck cut from breathable combed cotton.',
    details: ['100% combed cotton', 'Regular fit', 'Ribbed crew neckline', 'Machine wash cold'],
    rating: 4.4,
    reviews: 128,
    featured: true,
    newArrival: false,
    bestSeller: true,
    trending: true
  },
  {
    id: 2,
    name: 'Men Light Brown Simple T-Shirt',
    price: 999,
    image: './Men Tshirt image 2.avif',
    category: 'men',
    subcategory: 'Men T-Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'A soft earth-tone tee that pairs with almost everything you own.',
    details: ['Cotton jersey', 'Relaxed fit', 'Shoulder taping', 'Machine wash cold'],
    rating: 4.2,
    reviews: 86,
    featured: true,
    newArrival: false,
    bestSeller: true,
    trending: false
  },
  {
    id: 3,
    name: 'Men Brown T-Shirt',
    price: 1099,
    image: './Men Tshirt image 3.avif',
    category: 'men',
    subcategory: 'Men T-Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'A deep brown staple with a heavier hand-feel for cooler days.',
    details: ['220 GSM cotton', 'Regular fit', 'Pre-shrunk', 'Machine wash cold'],
    rating: 4.5,
    reviews: 74,
    featured: true,
    newArrival: false,
    bestSeller: false,
    trending: true
  },
  {
    id: 4,
    name: 'Men Casual T-Shirt',
    price: 1199,
    image: './Men Tshirt image 4.avif',
    category: 'men',
    subcategory: 'Men T-Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'An easy weekend tee with a slightly longer body and a soft drape.',
    details: ['Cotton-modal blend', 'Relaxed fit', 'Curved hem', 'Machine wash cold'],
    rating: 4.3,
    reviews: 51,
    featured: true,
    newArrival: true,
    bestSeller: true,
    trending: false
  },
  {
    id: 5,
    name: 'Men Everyday T-Shirt',
    price: 1299,
    image: './Men Tshirt image 5.avif',
    category: 'men',
    subcategory: 'Men T-Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'The tee you reach for on repeat, built to hold its shape.',
    details: ['Heavyweight cotton', 'Regular fit', 'Reinforced collar', 'Machine wash cold'],
    rating: 4.6,
    reviews: 205,
    featured: true,
    newArrival: true,
    bestSeller: true,
    trending: true
  },
  {
    id: 6,
    name: 'Men Maroon Shirt',
    price: 1399,
    image: './Men Shirt image 1.avif',
    category: 'men',
    subcategory: 'Men Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'A rich maroon shirt that dresses up jeans without trying too hard.',
    details: ['Cotton twill', 'Slim fit', 'Button-down collar', 'Machine wash cold'],
    rating: 4.4,
    reviews: 63,
    featured: true,
    newArrival: true,
    bestSeller: false,
    trending: false
  },
  {
    id: 7,
    name: 'Men Blue Shirt',
    price: 1499,
    image: './Men Shirt image 2.avif',
    category: 'men',
    subcategory: 'Men Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'A crisp blue shirt that moves from desk to dinner unchanged.',
    details: ['Wrinkle-resistant cotton', 'Slim fit', 'Spread collar', 'Machine wash cold'],
    rating: 4.5,
    reviews: 142,
    featured: true,
    newArrival: true,
    bestSeller: true,
    trending: true
  },
  {
    id: 8,
    name: 'Men Party Wear Black Shirt',
    price: 1599,
    image: './Men Shirt image 3.avif',
    category: 'men',
    subcategory: 'Men Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'A sheen-finish black shirt made for evenings out.',
    details: ['Satin-touch weave', 'Slim fit', 'Concealed placket', 'Dry clean recommended'],
    rating: 4.7,
    reviews: 97,
    featured: true,
    newArrival: true,
    bestSeller: true,
    trending: false
  },
  {
    id: 9,
    name: 'Men Formal Brown Shirt',
    price: 1699,
    image: './Men Shirt image 4.avif',
    category: 'men',
    subcategory: 'Men Shirt',
    sizes: SIZE_RUNS.adult,
    description: 'A structured formal shirt in a warm brown that reads softer than navy.',
    details: ['Two-ply cotton', 'Tailored fit', 'French placket', 'Machine wash cold'],
    rating: 4.3,
    reviews: 44,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: true
  },

  // ---------------- Women ----------------
  {
    id: 10,
    name: 'Women Floral Dress',
    price: 1799,
    image: './Women Dresses 1.jpg',
    category: 'women',
    subcategory: 'Women Dresses',
    sizes: SIZE_RUNS.adult,
    description: 'A flowing floral print dress that works for brunch or a garden party.',
    details: ['Viscose crepe', 'Fit and flare', 'Concealed back zip', 'Hand wash cold'],
    rating: 4.6,
    reviews: 188,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: false
  },
  {
    id: 11,
    name: 'Women A-Line Dress',
    price: 1899,
    image: './Women Dresses 2.jpg',
    category: 'women',
    subcategory: 'Women Dresses',
    sizes: SIZE_RUNS.adult,
    description: 'A classic A-line silhouette that skims rather than clings.',
    details: ['Cotton poplin', 'A-line cut', 'Side pockets', 'Machine wash cold'],
    rating: 4.5,
    reviews: 121,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: true
  },
  {
    id: 12,
    name: 'Women Wrap Midi Dress',
    price: 1999,
    image: './Women Dresses 3.jpg',
    category: 'women',
    subcategory: 'Women Dresses',
    sizes: SIZE_RUNS.adult,
    description: 'A true wrap dress with an adjustable tie, so the fit is yours.',
    details: ['Soft georgette', 'Wrap front with tie', 'Midi length', 'Hand wash cold'],
    rating: 4.4,
    reviews: 69,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false
  },
  {
    id: 13,
    name: 'Women Summer Maxi Dress',
    price: 2099,
    image: './Women Dresses 4.jpg',
    category: 'women',
    subcategory: 'Women Dresses',
    sizes: SIZE_RUNS.adult,
    description: 'A breezy full-length maxi in a lightweight weave for hot afternoons.',
    details: ['Airy cotton blend', 'Maxi length', 'Adjustable straps', 'Machine wash cold'],
    rating: 4.7,
    reviews: 156,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: true
  },
  {
    id: 14,
    name: 'Women Embroidered Kurta Set',
    price: 2199,
    image: './Women ethnic Dresses 1.jpg',
    category: 'women',
    subcategory: 'Women Ethnic Wear',
    sizes: SIZE_RUNS.adult,
    description: 'A hand-embroidered kurta with matching palazzo, sold as a ready set.',
    details: ['Cotton with thread embroidery', 'Kurta and palazzo included', 'Side slits', 'Dry clean recommended'],
    rating: 4.6,
    reviews: 203,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: false
  },
  {
    id: 15,
    name: 'Women Silk Anarkali',
    price: 2299,
    image: './Women ethnic Dresses 2.jpg',
    category: 'women',
    subcategory: 'Women Ethnic Wear',
    sizes: SIZE_RUNS.adult,
    description: 'A floor-sweeping anarkali with the quiet shine of art silk.',
    details: ['Art silk', 'Flared anarkali cut', 'Dupatta included', 'Dry clean only'],
    rating: 4.8,
    reviews: 174,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: true
  },
  {
    id: 16,
    name: 'Women Printed Saree',
    price: 2399,
    image: './Women ethnic Dresses 3.jpg',
    category: 'women',
    subcategory: 'Women Ethnic Wear',
    sizes: SIZE_RUNS.free,
    description: 'A printed saree in a soft drape, with an unstitched blouse piece.',
    details: ['6.3 m saree with 0.8 m blouse piece', 'Soft georgette drape', 'Blouse piece unstitched', 'Dry clean recommended'],
    rating: 4.3,
    reviews: 91,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false
  },
  {
    id: 17,
    name: 'Women Festive Lehenga',
    price: 2499,
    image: './Women ethnic Dresses 4.jpg',
    category: 'women',
    subcategory: 'Women Ethnic Wear',
    sizes: SIZE_RUNS.adult,
    description: 'A celebration lehenga with a full flare and detailed border work.',
    details: ['Lehenga, blouse and dupatta', 'Heavy border work', 'Concealed side zip', 'Dry clean only'],
    rating: 4.7,
    reviews: 132,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: true
  },

  // ---------------- Kids ----------------
  {
    id: 18,
    name: 'Kids Festive Kurta Set',
    price: 1299,
    image: './Ethnic kids wear.avif',
    category: 'kids',
    subcategory: 'Kids Ethnic Wear',
    sizes: SIZE_RUNS.kids,
    description: 'A festive kurta and pyjama set that survives a full day of celebrating.',
    details: ['Soft cotton blend', 'Kurta and pyjama included', 'Pull-on elastic waist', 'Machine wash cold'],
    rating: 4.5,
    reviews: 58,
    featured: true,
    newArrival: true,
    bestSeller: true,
    trending: true
  },
  {
    id: 19,
    name: 'Kids Embroidered Ethnic Set',
    price: 1399,
    image: './Ethnic kids wear 2.webp',
    category: 'kids',
    subcategory: 'Kids Ethnic Wear',
    sizes: SIZE_RUNS.kids,
    description: 'Bright traditional detailing on a set made for photographs.',
    details: ['Cotton with thread work', 'Two-piece set', 'Tagless neck label', 'Machine wash cold'],
    rating: 4.4,
    reviews: 37,
    featured: true,
    newArrival: true,
    bestSeller: false,
    trending: true
  },
  {
    id: 20,
    name: 'Kids Everyday Casual Set',
    price: 899,
    image: './kids-wear-everyday.jpg',
    category: 'kids',
    subcategory: 'Kids Casual',
    sizes: SIZE_RUNS.kids,
    description: 'An easy pull-on set for school runs, parks and everything after.',
    details: ['Breathable cotton', 'Top and bottom set', 'Elastic waistband', 'Machine wash warm'],
    rating: 4.2,
    reviews: 64,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: false
  },
  {
    id: 21,
    name: 'Kids Playtime Casual Set',
    price: 999,
    image: './kids-wear-playtime.webp',
    category: 'kids',
    subcategory: 'Kids Casual',
    sizes: SIZE_RUNS.kids,
    description: 'Stretchy, scuff-friendly clothes built for actual playing.',
    details: ['Cotton with added stretch', 'Top and bottom set', 'Flat seams for comfort', 'Machine wash warm'],
    rating: 4.3,
    reviews: 45,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: false
  }
];

// Labels used by the filter sidebar, breadcrumbs and product cards.
const CATEGORY_LABELS = {
  men: 'Men',
  women: 'Women',
  kids: 'Kids'
};

const SUBCATEGORIES = [
  { value: 'Men T-Shirt', label: 'Men T-Shirts', category: 'men' },
  { value: 'Men Shirt', label: 'Men Shirts', category: 'men' },
  { value: 'Women Dresses', label: 'Women Dresses', category: 'women' },
  { value: 'Women Ethnic Wear', label: 'Women Ethnic Wear', category: 'women' },
  { value: 'Kids Ethnic Wear', label: 'Kids Ethnic Wear', category: 'kids' },
  { value: 'Kids Casual', label: 'Kids Casual', category: 'kids' }
];
